#baseurl      = "localhost" #"thesis.nordskov.net" #"usb-honeypot.compute.dtu.dk"
title        = "Thesis Info"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 1

#[author]
#  name = "Johannes Nordskov Pedersen"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

# Subtitle for home
#  homeSubtitle = "Master Thesis Information Page"

  disableReadOtherPosts = true
  enableSharingButtons = false
  enableGlobalLanguageMenu = false
  enableThemeToggle = true

  enableRobotsTXT = false
  enableGitInfo   = false
  enableEmoji     = false
  enableMissingTranslationPlaceholders = false
  disableRSS     = true
  disableSitemap = true
  disable404     = true
  disableHugoGeneratorInject = false

#  PygmentsCodeFences = true
#  PygmentsStyle = "monokai"

[languages]

  [languages.en]
#    languageCode = 'en-US'
#    languageName = 'English'
    title = "Thesis Info"
    weight = 1

    [languages.en.params.logo]
      logoText = "Thesis Info"
      logoHomeLink = "/"

  [languages.da]
 #   languageCode = 'da-DK'  
 #   languageName = 'Danish'
    title = "Speciale Info"
    weight = 1
    
    [languages.da.params.logo]
      logoText = "Speciale Info"
      logoHomeLink = "/da/"
  
  [params.footer]
#    trademark = 2023
    rss = false
    copyright = false
    author = false

    topText = [
      "<a href=\"https://www.compute.dtu.dk\">DTU Compute</a>",
      "Bygning 324",
      "2800 Kgs. Lyngby",
    ]
    
    bottomText = [
      "Department of Applied Mathematics and Computer Science"
  ]

#  [[menu.main]]
  #  identifier = "/page/contact"
  #  name       = "Contact"
  #  url        = "/page/contact"

